#pragma once

// Self-contained host implementation of the LC pipeline DIFFMS_2 + BIT_2 + RZE_2.
//
// The chunk-based bitstream format is byte-for-byte compatible with the standalone
// CPU compressor/decompressor generated by the upstream LC framework
// (generate_standalone_CPU_compressor_decompressor.py) for the same pipeline, so a
// payload produced here can be decoded by the reference tool and vice versa.

#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <limits>
#include <stdexcept>

namespace photonzip {
namespace lc {

using byte = unsigned char;

// Pipeline constants, identical to the upstream LC CPU framework.
static const int CS = 1024 * 16;  // chunk size in bytes, must be a multiple of 8
static const int TPB = 512;       // threads per block (unused on the CPU path)
#if defined(__AMDGCN_WAVEFRONT_SIZE) && (__AMDGCN_WAVEFRONT_SIZE == 64)
#define LC_WS 64
#else
#define LC_WS 32
#endif
#ifndef WS
#define WS LC_WS
#endif

// The LC component headers expect the symbols above (byte/CS/WS) to already be
// visible. They define `static inline` helpers, so including them inside this
// namespace keeps them out of the global scope.
#include "lossless/lc/include/macros.h"
#include "lossless/lc/components/h_DIFFMS_2.h"
#include "lossless/lc/components/h_BIT_2.h"
#include "lossless/lc/components/h_RZE_2.h"

// Upper bound on the encoded size for a given input size.
inline long long max_encoded_size(long long insize) {
  const long long chunks = (insize + CS - 1) / CS;  // round up
  return 2 * static_cast<long long>(sizeof(long long)) +
         chunks * static_cast<long long>(sizeof(unsigned short)) + chunks * CS;
}

// Reads the original (decoded) size stored in the LC header.
inline long long decoded_size(const byte* const input) {
  long long value = 0;
  std::memcpy(&value, input, sizeof(value));
  return value;
}

inline void h_encode(const byte* const input, const long long insize,
                     byte* const output, long long& outsize) {
  const long long chunks = (insize + CS - 1) / CS;  // round up
  long long* const head_out = reinterpret_cast<long long*>(output);
  unsigned short* const size_out = reinterpret_cast<unsigned short*>(&head_out[1]);
  byte* const data_out = reinterpret_cast<byte*>(&size_out[chunks]);
  long long* const carry = new long long[chunks == 0 ? 1 : chunks];
  if (chunks > 0) {
    std::memset(carry, 0, chunks * sizeof(long long));
  }

  #pragma omp parallel for schedule(dynamic, 1)
  for (long long chunkID = 0; chunkID < chunks; chunkID++) {
    long long chunk1[CS / sizeof(long long)];
    long long chunk2[CS / sizeof(long long)];
    byte* in = reinterpret_cast<byte*>(chunk1);
    byte* out = reinterpret_cast<byte*>(chunk2);
    const long long base = chunkID * CS;
    const int osize = static_cast<int>(std::min(static_cast<long long>(CS), insize - base));
    std::memcpy(out, &input[base], osize);

    int csize = osize;
    bool good = true;
    if (good) {
      std::swap(in, out);
      good = h_DIFFMS_2(csize, in, out);
    }
    if (good) {
      std::swap(in, out);
      good = h_BIT_2(csize, in, out);
    }
    if (good) {
      std::swap(in, out);
      good = h_RZE_2(csize, in, out);
    }

    long long offs = 0LL;
    if (chunkID > 0) {
      do {
        #pragma omp atomic read
        offs = carry[chunkID - 1];
      } while (offs == 0);
      #pragma omp flush
    }
    if (good && (csize < osize)) {
      #pragma omp atomic write
      carry[chunkID] = (offs + static_cast<long long>(csize));
      size_out[chunkID] = static_cast<unsigned short>(csize);
      std::memcpy(&data_out[offs], out, csize);
    } else {
      #pragma omp atomic write
      carry[chunkID] = (offs + static_cast<long long>(osize));
      size_out[chunkID] = static_cast<unsigned short>(osize);
      std::memcpy(&data_out[offs], &input[base], osize);
    }
  }

  head_out[0] = insize;
  outsize = (chunks == 0) ? (data_out - output)
                          : (&data_out[carry[chunks - 1]] - output);
  delete[] carry;
}

inline void h_decode(const byte* const input, byte* const output, long long& outsize) {
  const long long* const head_in = reinterpret_cast<const long long*>(input);
  long long out_total = 0;
  std::memcpy(&out_total, head_in, sizeof(out_total));
  outsize = out_total;

  const long long chunks = (out_total + CS - 1) / CS;  // round up
  const unsigned short* const size_in =
      reinterpret_cast<const unsigned short*>(&head_in[1]);
  const byte* const data_in = reinterpret_cast<const byte*>(&size_in[chunks]);
  long long* const start = new long long[chunks == 0 ? 1 : chunks];

  long long pfs = 0;
  for (long long chunkID = 0; chunkID < chunks; chunkID++) {
    start[chunkID] = pfs;
    pfs += static_cast<long long>(size_in[chunkID]);
  }

  #pragma omp parallel for schedule(dynamic, 1)
  for (long long chunkID = 0; chunkID < chunks; chunkID++) {
    long long chunk1[CS / sizeof(long long)];
    long long chunk2[CS / sizeof(long long)];
    byte* in = reinterpret_cast<byte*>(chunk1);
    byte* out = reinterpret_cast<byte*>(chunk2);
    const long long base = chunkID * CS;
    const int osize = static_cast<int>(std::min(static_cast<long long>(CS), out_total - base));
    int csize = size_in[chunkID];
    if (csize == osize) {
      std::memcpy(&output[base], &data_in[start[chunkID]], osize);
    } else {
      std::memcpy(out, &data_in[start[chunkID]], csize);

      std::swap(in, out);
      h_iRZE_2(csize, in, out);
      std::swap(in, out);
      h_iBIT_2(csize, in, out);
      std::swap(in, out);
      h_iDIFFMS_2(csize, in, out);

      if (csize != osize) {
        delete[] start;
        throw std::runtime_error("LC decode chunk size mismatch.");
      }
      std::memcpy(&output[base], out, csize);
    }
  }

  delete[] start;
}

}  // namespace lc
}  // namespace photonzip
